### PR TITLE
Fix edit source to add changes

### LINKED ISSUE #1113: Edit source changes not being added to review changes
**Issue**

When editing from edit source changes are not being captured by review changes, the user will have to make any change within visualeditor and save, therefore edit source changes will be added to review.

### PR DESCRIPTION
**Pull request by TejBenamor**
resolves #1113

### CODE REVIEW

File: docker/resources/common-files/Common-fr.js [hunk 1]
```diff
@@ -893,20 +893,20 @@ mw.hook( 'wikipage.content' ).add( addBibSubsetMenu );
...
 
-            setTimeout(() => {
-                window.parent.postMessage({ type: 'saved-changes', articleId: page }, '*');
-            }, 100);
+            setTimeout(function () {
+                window.parent.postMessage({
+                    type: 'saved-changes',
+                    articleId: page
+                }, '*');
+            }, 50);
```
Comment (J43fura) [inline docker/resources/common-files/Common-fr.js]: What is the timeout for?

File: docker/resources/common-files/Common-fr.js [hunk 2]
```diff
@@ -891,6 +891,54 @@ mw.hook( 'wikipage.content' ).add( addBibSubsetMenu );
         };
       });
 
+				// Source Editor Save Handling
+	$(function() {
```
Comment (J43fura) [inline docker/resources/common-files/Common-fr.js]: remove extra tabs

**Review by J43fura — CHANGES_REQUESTED** [review]

File: docker/resources/common-files/Common-en.js [hunk 3]
```diff
@@ -339,5 +339,54 @@ mw.loader.using( [ 'mediawiki.util' ] ).done( function () {
...
       });
       
-} );
+// Source Editor Save Handling
+$(function() {
+  if (!isIframe) return;
+  
+  const wgAction = mw.config.get('wgAction');
+  
+  if (wgAction === 'edit' || wgAction === 'submit') {
```
Comment (J43fura) [inline docker/resources/common-files/Common-en.js]: why on 'edit' ?

Comment (TejBenamor) [reply docker/resources/common-files/Common-en.js]: I remove edit

**Review by J43fura — CHANGES_REQUESTED** [review]
@TejBenamor please explain the logic here

File: docker/resources/common-files/Common-en.js [hunk 4]
```diff
@@ -339,5 +339,54 @@ mw.loader.using( [ 'mediawiki.util' ] ).done( function () {
...
+    var editForm = document.getElementById('editform');
+    if (editForm) {
+      editForm.addEventListener('submit', function() {
+        try {
+          sessionStorage.setItem('wikiadviser_source_saved', 'true');
+          sessionStorage.setItem('wikiadviser_article_id', mw.config.get('wgPageName'));
```
[the remark this answers is not in the document]
Comment (J43fura) [reply docker/resources/common-files/Common-en.js]: What looping?

**Comment by J43fura** [comment]
I don't get point 1, is the event launched or not to begin with?

**Comment by J43fura** [comment]
What's the importance of point 4?

**Comment by J43fura** [comment]
> `wgPostEdit` approach: doesn't work for source editor it return `null`

Please make sure to do a change when saving, see the docs:
https://www.mediawiki.org/wiki/Manual:Interface/JavaScript#:~:text=saving%20an%20edit-,wgPostEdit,-String
image

**Comment by TejBenamor** [comment]
> you mentioned it returned `null`
> 
> > I tried `wgPostEdit` but not working in source editor as visual editor instead `wgAction` work on source editor

yes it not working and return null
