### PR TITLE
Fix email sending error and comment error to anonymous user 

### LINKED ISSUE #1083: sending email to anonymous sign-in
the error happen when send email to anonymous sign in because  they dont have mail address:

Image

anonymous sign-in should not delivred an email

### PR DESCRIPTION
**Pull request by TejBenamor**
resolves #1083

### CODE REVIEW

File: frontend/src/components/Diff/DiffItem.vue [hunk 1]
```diff
@@ -369,6 +369,10 @@ const previewDescription = computed(() => {
 });
 
 function getName(email: string) {
+  if (!email) {
+    return 'Unknown User';
```
Comment (J43fura) [inline frontend/src/components/Diff/DiffItem.vue:373]:
```suggestion
    return null;
```

File: supabase/functions/notification/handlers/handleEmailNotification.ts [hunk 2]
```diff
@@ -106,7 +106,8 @@ export async function sendEmailNotification(notification: Notification) {
 
     const html = buildHtmlEmail(subject, text, redirectUrl);
 
-    await transporter.sendMail({
```
Comment (J43fura) [inline supabase/functions/notification/handlers/handleEmailNotification.ts:109]: Why go through all the function and then exit?
please use an early return statement at the beggining of the function
```js
if (toEmail === null) return;
```

File: frontend/src/components/Diff/DiffItem.vue (hunk 1 above)
Comment (J43fura) [reply frontend/src/components/Diff/DiffItem.vue:373]: Return `null` instead of a custom string

**Review by J43fura — CHANGES_REQUESTED** [review]

File: supabase/functions/notification/handlers/handleEmailNotification.ts [hunk 3]
```diff
@@ -15,7 +15,7 @@ import {
 export async function sendEmailNotification(notification: Notification) {
   try {
     const toEmail = await getUserEmail(notification.user_id);
-    if (!toEmail) {
+    if (!toEmail ||toEmail === "Unknown User") {
```
Comment (J43fura) [inline supabase/functions/notification/handlers/handleEmailNotification.ts:18]: What is `||toEmail === "Unknown User"` for?

Comment (TejBenamor) [reply supabase/functions/notification/handlers/handleEmailNotification.ts:18]: The unknown user is from helpers :
`export async function getUserEmail(userId: string): Promise<string> {
  const supabase = createSupabaseAdmin();
  const user = await safeSingle<{ email: string }>(
    supabase.from('profiles').select('email').eq('id', userId)
  );
  return user?.email ?? 'Unknown User';
}`

File: frontend/src/components/Diff/DiffItem.vue [hunk 4]
```diff
@@ -369,6 +369,10 @@ const previewDescription = computed(() => {
 });
 
 function getName(email: string) {
```
Comment (J43fura) [inline frontend/src/components/Diff/DiffItem.vue:371]: what is this used for?

**Comment by J43fura** [comment]
I no longer understand this PR, @TejBenamor Please elaborate

File: frontend/src/components/Diff/DiffItem.vue (hunk 4 above)
Comment (TejBenamor) [reply frontend/src/components/Diff/DiffItem.vue:371]: when anonymous user add a comment or user add a comment on revision it trigger error.

File: supabase/functions/notification/utils/helpers.ts [hunk 5]
```diff
@@ -10,12 +10,12 @@ export async function getArticleTitle(articleId: string): Promise<string> {
...
 }
 
-export async function getUserEmail(userId: string): Promise<string> {
+export async function getUserEmail(userId: string): Promise<string | null> {
   const supabase = createSupabaseAdmin();
   const user = await safeSingle<{ email: string }>(
     supabase.from('profiles').select('email').eq('id', userId)
   );
-  return user?.email ?? 'Unknown User';
+  return user?.email ?? null;
```
[the remark this answers is not in the document]
Comment (TejBenamor) [reply supabase/functions/notification/utils/helpers.ts:18]: email could be null  in anonymous user so the function fetch email if exist or null

File: frontend/src/components/Diff/DiffItem.vue (hunk 4 above)
Comment (J43fura) [reply frontend/src/components/Diff/DiffItem.vue:371]: It should be the user's Name, if there is no Name, then Email.

File: supabase/functions/notification/utils/helpers.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (J43fura) [reply supabase/functions/notification/utils/helpers.ts:18]: and where is `getUserEmail` being used?, what does this change resolve?
Also this doesnt answer:
> what is *the value of* `user?.email` if email doesnt exist?

**Review by J43fura — CHANGES_REQUESTED** [review]

File: supabase/functions/notification/utils/helpers.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (TejBenamor) [reply supabase/functions/notification/utils/helpers.ts:18]: yes in `sendEmailNotification` function implemented `if (!toEmail)` then early return and exit , sendEmail are work if there an email address in variable `toEmail`

[the remark this answers is not in the document]
Comment (J43fura) [reply supabase/functions/notification/utils/helpers.ts:18]: > what is *the value of* `user?.email` if email doesnt exist?

File: frontend/src/components/Diff/DiffItem.vue [hunk 6]
```diff
@@ -368,11 +368,17 @@ const previewDescription = computed(() => {
...
 
-function getName(email: string) {
-  return (
-    email.substring(0, MAX_EMAIL_LENGTH) +
-    (email.length > MAX_EMAIL_LENGTH ? '...' : '')
-  );
+function getName(user: { display_name?: string | null; email: string }) {
+  if (user.display_name && user.display_name.trim() !== '') {
+    return user.display_name;
+  }
```
[the remark this answers is not in the document]
Comment (TejBenamor) [reply frontend/src/components/Diff/DiffItem.vue:374]: yes in normal user is working display_name if not email but anonymous not working

[the remark this answers is not in the document]
Comment (J43fura) [reply frontend/src/components/Diff/DiffItem.vue:374]: anonymous users do have `display_name`, please make sure that we are also getting `user.display_name`  in `comments`

**Review by J43fura — CHANGES_REQUESTED** [review]

**Review by J43fura — APPROVED** [review]
